; SETUP
	ORG 8000H
	MOV A, #11111110B

; MAIN LOOP
LOOP:
	MOV P1, A
	RR A
	; ROTATE LIGHT, ALSO CAN ROTATE RIGHT 
	; BY USING "RR" CMD
	CALL DELAY
	JMP LOOP

; DELAY PROCEDURE
DELAY: MOV R0, #0FFH
DELAY1: MOV R1, #0FFH
;DELAY2: NOP

DELAY3:	;DJNZ R1, DELAY2 ;3 CLOCK CYCLE SPENT
	DJNZ R1, DELAY3 ;2 CLOCK CYCLE SPENT
	DJNZ R0, DELAY1
	RET

END