	ORG 8000H
	; MEMORY LOCATIONS OF SEVEN-SEGMENT ARRAY
	; SEG1 IS THE LEFT PAIR
	; SEG2 IS THE MIDDLE PAIR
	; SEG3 IS THE RIGHT PAIR

	SEG1 EQU 0FFC3h
	SEG2 EQU 0FFC2h
	SEG3 EQU 0FFC1h

	; DISPLAY '23' ON MIDDLE TWO DISPLAYS
	; IN THE SEVEN-SEGMENT ARRAY

START:
	MOV A, #00100011b
	MOV DPTR, #SEG2
	; Only MOVX ABLE TO STORE EXTERNAL 16BIT RAM
	MOVX @DPTR, A
	
	JMP $
END