	ORG 8000H
	; Memory Location of 7-Segment Disp
	; similar to #define in C Language
	SEVENSEG EQU 0FFC0H

START:
	MOV A, #11111000B
	CALL DISPLAY

LOOP:
	CALL DISPLAY
	JMP LOOP

; SET SEVENSEG DATA POINTER TO CERTAIN VALUE
DISPLAY:
	MOV DPTR, #SEVENSEG
	MOVX @DPTR, A
	RET

FINISH: JMP FINISH 